name: CD Workflow 2

on:
  push:
    branches:
      - azure-deploy

env:
  IMAGE_NAME: ghcr.io/${{github.repository}}:${{github.run_number}}-${{github.run_attempt}}

permissions:
  contents: 'read'
  packages: 'write'

jobs:
  cd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to GitHub container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - id: imagename
        uses: ASzc/change-string-case-action@v5
        with:
          string: ${{env.IMAGE_NAME}}

      - name: Build and push docker image
        run: |
          docker build -t ${{steps.imagename.outputs.lowercase}} .
          docker push ${{steps.imagename.outputs.lowercase}}

      - name: Deploy to Azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_APP_NAME }}
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          images: ${{steps.imagename.outputs.lowercase}}
